name: Send message to Telegram
description: Send message to Telegram
inputs:
  token:
    description: telegram token
    required: true
  chat_id:
    description: telegram chat id
    required: true
  chat_thread_id:
    description: telegram chat thread id
    required: true
  message:
    description: message
    required: true
  host:
    description: telegram host
    required: false
    default: "api.telegram.org"

branding:
  icon: 'message-square'
  color: 'blue'
runs:
  using: composite
  steps:
    - name: Send message
      run: |
        curl -s -X POST 'https://${{ inputs.host }}/bot${{ inputs.token }}/sendMessage' \
        -d "chat_id=${{ inputs.chat_id }}&text=${{ inputs.message }}&message_thread_id=${{ inputs.chat_thread_id }}"
      shell: bash
